version: "3"

ports:
  - "80:80"
  - "443:443"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build: .
    depends_on:
      - redis
    environment:
      DEMO_APP_ADDR: :8080
      DEMO_REDIS_ADDR: redis:6379

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - app

volumes:
  redis_data: